services:
  portland-maps-scraper:
    build: https://github.com/SethDowden/portland-maps-scraper.git#main
    restart: unless-stopped

    environment:
      APIKEY: "YOUR_APIKEY"
      TZ: "YOUR_TIME_ZONE"
    volumes:
      - /data:/data